export const CANDIDATES = [
  {
    id: 'c1',
    name: 'Aryan Mehta',
    party: 'Progress Alliance',
    bio: 'Champion of digital governance and youth empowerment across the nation.',
    emoji: '🌟',
    color: 'rgba(245,198,224,0.7)',
    votes: 1240,
  },
  {
    id: 'c2',
    name: 'Priya Sharma',
    party: 'United Front',
    bio: 'Environmental advocate committed to sustainable development and green energy.',
    emoji: '🌿',
    color: 'rgba(184,240,216,0.7)',
    votes: 980,
  },
  {
    id: 'c3',
    name: 'Rahul Verma',
    party: 'National Reform',
    bio: 'Former IAS officer focusing on anti-corruption measures and civic transparency.',
    emoji: '⚖️',
    color: 'rgba(184,216,240,0.7)',
    votes: 856,
  },
  {
    id: 'c4',
    name: 'Sneha Gupta',
    party: "People's Voice",
    bio: 'Grassroots leader from rural background advocating for farmer rights and welfare.',
    emoji: '🌾',
    color: 'rgba(245,216,176,0.7)',
    votes: 712,
  },
  {
    id: 'c5',
    name: 'Vikram Singh',
    party: 'Tech Forward',
    bio: 'Silicon Valley returnee with a bold vision for smart cities and startup ecosystems.',
    emoji: '💡',
    color: 'rgba(212,184,240,0.7)',
    votes: 430,
  },
]
